[manager]

keymap = [

  # Spotting
  { on = "<Tab>", run = "spot", desc = "Spot hovered file" },

  { on = [
    "M",
    "a",
  ], run = "plugin autofilter --args='save'", desc = "Add filter for this folder" },
  { on = [
    "M",
    "d",
  ], run = "plugin autofilter --args='delete'", desc = "Delete filter for this folder" },
  { on = [
    "M",
    "D",
  ], run = "plugin autofilter --args='delete_all'", desc = "Delete all filter" },
  { on = [
    "O",
    "a",
  ], run = "plugin autosort --args='save'", desc = "Add sort for this folder" },
  { on = [
    "O",
    "d",
  ], run = "plugin autosort --args='delete'", desc = "Delete sort for this folder" },
  { on = [
    "O",
    "D",
  ], run = "plugin autosort --args='delete_all'", desc = "Delete all filter" },

  { on = [
    "<A-k>",
  ], run = "plugin arrow-parent --args=-1", desc = "arrow parent up" },
  { on = [
    "<A-j>",
  ], run = "plugin arrow-parent --args=1", desc = "arrow parent down" },
  { on = [
    "U",
  ], run = "plugin cd-last", desc = "cd last path" },

  { on = [
    "u",
    "a",
  ], run = "plugin bookmarks --args='save'", desc = "Add hovered as bookmark" },
  { on = [
    "u",
    "m",
  ], run = "plugin bookmarks --args='modify'", desc = "modify a bookmarks key to hovered" },
  { on = [
    "u",
    "g",
  ], run = "plugin bookmarks --args='jump'", desc = "Jump to a bookmark" },
  { on = [
    "u",
    "d",
  ], run = "plugin bookmarks --args='delete'", desc = "Delete a bookmark" },
  { on = [
    "u",
    "D",
  ], run = "plugin bookmarks --args='delete_all'", desc = "Delete all bookmarks" },
  { on = [
    "u",
    "l",
  ], run = "plugin lastopen --args='jump'", desc = "jump to last open file" },
  { on = [
    "u",
    "n",
  ], run = "plugin mount", desc = "mount manager" },

  { on = [
    "I",
  ], run = "plugin keyjump --args='global'", desc = "keyjump" },
  { on = [
    "i",
  ], run = "plugin easyjump --args=''", desc = "easyjump" },
  { on = [
    "s",
  ], run = "plugin searchjump --args=''", desc = "searchjump" },

  # Linemode
  { on = [
    "z",
    "s",
  ], run = "linemode size", desc = "Set linemode to size" },
  { on = [
    "z",
    "p",
  ], run = "linemode permissions", desc = "Set linemode to permissions" },
  { on = [
    "z",
    "m",
  ], run = "linemode mtime", desc = "Set linemode to mtime" },
  { on = [
    "z",
    "c",
  ], run = "linemode ctime", desc = "Set linemode to ctime" },
  { on = [
    "z",
    "n",
  ], run = "linemode none", desc = "Set linemode to none" },
  { on = [
    "z",
    "o",
  ], run = "linemode owner", desc = "Set linemode to owner" },

  { on = [
    "u",
    "i",
  ], run = "plugin cmd --args='lazygit'", desc = "lazygit" },
  { on = [
    "u",
    "f",
  ], run = '''shell ' QT_QPA_PLATFORM=xcb ~/deskenv/master/qxdrag/qxdrag.py -x -e -b -p "$1"' --confirm''', desc = "dragon x11" },
  { on = [
    "u",
    "w",
  ], run = '''shell ' QT_QPA_PLATFORM=wayland ~/deskenv/master/qxdrag/qxdrag.py -x -e -b -p "$1"' --confirm''', desc = "dragon wayland" },
  # { on = [ "u","w" ], run = '''shell ' GDK_BACKEND=wayland dragon -x -i -T "$1"' --confirm''',desc="dragon wayland" },
  # { on = [ "u","r" ], run = '''shell ' GDK_BACKEND=x11 dragon -x -i -T "$1"' --confirm''',desc="dragon wayland" },

  { on = [
    "<Esc>",
  ], run = "escape", desc = "Exit visual mode, clear selected, or cancel search" },
  { on = [
    "q",
  ], run = "quit", desc = "Exit the process" },
  { on = [
    "<C-q>",
  ], run = "close", desc = "Close the current tab, or quit if it is last tab" },
  { on = [
    "<C-z>",
  ], run = "suspend", desc = "Suspend the process" },

  # Navigation
  { on = [
    "k",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "j",
  ], run = "arrow 1", desc = "Move cursor down" },

  { on = [
    "K",
  ], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = [
    "J",
  ], run = "arrow 5", desc = "Move cursor down 5 lines" },

  # { on = [ "<C-k>" ], run = "arrow -20", desc = "Move cursor up 20 lines" },
  # { on = [ "<C-j>" ], run = "arrow 20",  desc = "Move cursor up 20 lines" },
  { on = [
    "<C-k>",
  ], run = "arrow -100%", desc = "Move cursor prev page" },
  { on = [
    "<C-j>",
  ], run = "arrow 100%", desc = "Move cursor next page" },

  { on = [
    "b",
  ], run = "arrow top", desc = "Move cursor begin lines" },
  { on = [
    "e",
  ], run = "arrow bot", desc = "Move cursor end lines" },

  { on = [
    "h",
  ], run = "leave", desc = "Go back to the parent directory" },
  { on = [
    "l",
  ], run = "enter", desc = "Enter the child directory" },

  { on = [
    "H",
  ], run = "back", desc = "Go back to the previous directory" },
  { on = [
    "L",
  ], run = "forward", desc = "Go forward to the next directory" },

  { on = [
    "<S-A-K>",
  ], run = "seek -5", desc = "seek up 5 units in the preview" },
  { on = [
    "<S-A-J>",
  ], run = "seek 5", desc = "seek down 5 units in the preview" },

  { on = [
    "<Up>",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "<Down>",
  ], run = "arrow 1", desc = "Move cursor down" },
  { on = [
    "<Left>",
  ], run = "leave", desc = "Go back to the parent directory" },
  { on = [
    "<Right>",
  ], run = "enter", desc = "Enter the child directory" },

  # Selection
  { on = [
    "<Space>",
  ], run = [
    "toggle --state=none",
    "arrow 1",
  ], desc = "Toggle the current selection state" },
  { on = [
    "v",
  ], run = "visual_mode", desc = "Enter visual mode (selection mode)" },
  { on = [
    "V",
  ], run = "visual_mode --unset", desc = "Enter visual mode (unset mode)" },
  { on = [
    "<C-a>",
  ], run = "toggle_all --state=true", desc = "Select all files" },
  { on = [
    "<C-r>",
  ], run = "toggle_all --state=none", desc = "Inverse selection of all files" },

  # Operation
  { on = [
    "u",
    "s",
  ], run = '''shell "$SHELL" --block --confirm''', desc = "Open shell here" },
  { on = [
    "o",
  ], run = "open --interactive --hovered", desc = "Open the currsor hovered files interactively" },
  # { on = [ "O" ],   		run = "open",                   desc = "Open the selected files" },
  # { on = [ "<Enter>" ],   run = "open --hovered",         desc = "Open the currsor hovered files" },
  { on = [
    "<Enter>",
  ], run = "plugin lastopen --args='open'", desc = "Open the currsor hovered files" },
  { on = [
    "y",
  ], run = "yank", desc = "Copy the selected files" },
  { on = [
    "x",
  ], run = "yank --cut", desc = "Cut the selected files" },
  { on = [
    "p",
  ], run = "paste", desc = "Paste the files" },
  { on = [
    "P",
  ], run = "paste --force", desc = "Paste the files (overwrite if the destination exists)" },
  { on = [
    "k",
  ], run = "paste --follow", desc = "Paste the files (follow the symlinks)" },
  { on = [
    "K",
  ], run = "paste --follow --force", desc = "Paste the files (overwrite + follow)" },
  { on = [
    "d",
  ], run = "remove", desc = "Move the files to the trash" },
  { on = [
    "D",
  ], run = "remove --permanently", desc = "Permanently delete the files" },
  { on = [
    "a",
  ], run = "create", desc = "Create a file or directory (ends with / for directories)" },
  { on = [
    "r",
  ], run = "rename", desc = "Rename a file or directory" },
  { on = [
    ";",
  ], run = "shell --interactive", desc = "Run a shell command" },
  { on = [
    ":",
  ], run = "shell --block --interactive", desc = "Run a shell command (block the UI until the command finishes)" },
  { on = [
    ".",
  ], run = "hidden toggle", desc = "Toggle the visibility of hidden files" },

  # Filter & file
  { on = [
    "f",
    "t",
  ], run = "filter --smart", desc = "Filter the files" },
  # { on = [ "f","d" ],     run = "search fd",              desc = "Search files by name using fd" },
  { on = [
    "f",
    "g",
  ], run = "plugin fg --args='rg'", desc = "find file by content (ripgrep match)" },
  { on = [
    "f",
    "G",
  ], run = "plugin fg", desc = "find file by content (fuzzy match)" },
  { on = [
    "f",
    "e",
  ], run = "search none", desc = "Cancel the ongoing search" },
  { on = [
    "f",
    "z",
  ], run = "plugin zoxide", desc = "Jump to a directory using zoxide" },
  { on = [
    "f",
    "f",
  ], run = "plugin fg --args='fzf'", desc = "Jump to a directory, or reveal a file using fzf" },
  { on = [
    "f",
    "n",
  ], run = "find --smart", desc = "Find next file" },
  { on = [
    "f",
    "p",
  ], run = "find --previous --smart", desc = "Find previous file" },
  { on = [
    "n",
  ], run = "find_arrow", desc = "Go to next found file" },
  { on = [
    "N",
  ], run = "find_arrow --previous", desc = "Go to previous found file" },


  # Copy
  { on = [
    "c",
    "c",
  ], run = "copy path", desc = "cp absolute path" },
  { on = [
    "c",
    "d",
  ], run = "copy dirname", desc = "cp parent path" },
  { on = [
    "c",
    "f",
  ], run = "copy filename", desc = "cp filename" },
  { on = [
    "c",
    "n",
  ], run = "copy name_without_ext", desc = "cp filename without ext" },


  # Sort
  # Sorting
  { on = [
    "m",
    "M",
  ], run = [
    "sort mtime --reverse=no",
  ], desc = "Sort by modified time" },
  { on = [
    "m",
    "m",
  ], run = [
    "sort mtime --reverse",
  ], desc = "Sort by modified time (reverse)" },
  { on = [
    "m",
    "b",
  ], run = [
    "sort btime --reverse=no",
  ], desc = "Sort by birth time" },
  { on = [
    "m",
    "B",
  ], run = [
    "sort btime --reverse",
  ], desc = "Sort by birth time (reverse)" },
  { on = [
    "m",
    "e",
  ], run = "sort extension --reverse=no", desc = "Sort by extension" },
  { on = [
    "m",
    "E",
  ], run = "sort extension --reverse", desc = "Sort by extension (reverse)" },
  { on = [
    "m",
    "a",
  ], run = "sort alphabetical --reverse=no", desc = "Sort alphabetically" },
  { on = [
    "m",
    "A",
  ], run = "sort alphabetical --reverse", desc = "Sort alphabetically (reverse)" },
  { on = [
    "m",
    "n",
  ], run = "sort natural --reverse=no", desc = "Sort naturally" },
  { on = [
    "m",
    "N",
  ], run = "sort natural --reverse", desc = "Sort naturally (reverse)" },
  { on = [
    "m",
    "s",
  ], run = [
    "sort size --reverse=no",
  ], desc = "Sort by size" },
  { on = [
    "m",
    "S",
  ], run = [
    "sort size --reverse",
  ], desc = "Sort by size (reverse)" },
  { on = [
    "m",
    "r",
  ], run = "sort random --reverse=no", desc = "Sort randomly" },
  # Tabs
  { on = [
    "t",
  ], run = "tab_create --current", desc = "Create a new tab using the current path" },

  { on = [
    "1",
  ], run = "tab_switch 0", desc = "Switch to the first tab" },
  { on = [
    "2",
  ], run = "tab_switch 1", desc = "Switch to the second tab" },
  { on = [
    "3",
  ], run = "tab_switch 2", desc = "Switch to the third tab" },
  { on = [
    "4",
  ], run = "tab_switch 3", desc = "Switch to the fourth tab" },
  { on = [
    "5",
  ], run = "tab_switch 4", desc = "Switch to the fifth tab" },
  { on = [
    "6",
  ], run = "tab_switch 5", desc = "Switch to the sixth tab" },
  { on = [
    "7",
  ], run = "tab_switch 6", desc = "Switch to the seventh tab" },
  { on = [
    "8",
  ], run = "tab_switch 7", desc = "Switch to the eighth tab" },
  { on = [
    "9",
  ], run = "tab_switch 8", desc = "Switch to the ninth tab" },

  { on = [
    "<A-h>",
  ], run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
  { on = [
    "<A-l>",
  ], run = "tab_switch 1 --relative", desc = "Switch to the next tab" },

  # { on = [ "<A-->" ], run = "tab_swap -1", desc = "Swap the current tab with the previous tab" },
  # { on = [ "<A-=>" ], run = "tab_swap 1",  desc = "Swap the current tab with the next tab" },

  # Tasks
  { on = [
    "w",
  ], run = "tasks_show", desc = "Show the tasks manager" },

  # Goto
  { on = [
    "g",
    "w",
  ], run = "cd ~/Documents/WeChat_Data/home", desc = "Go to weixin" },
  { on = [
    "g",
    "h",
  ], run = "cd ~", desc = "Go to home" },
  { on = [
    "g",
    "c",
  ], run = "cd ~/.config", desc = "Go to config" },
  { on = [
    "g",
    "u",
  ], run = "cd /media/UUI/", desc = "Go to Mobile disk" },
  { on = [
    "g",
    "d",
  ], run = "cd ~/Downloads", desc = "Go to downloads" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/Videos", desc = "Go to videos" },
  { on = [
    "g",
    "m",
  ], run = "cd ~/Music", desc = "Go to musics" },
  { on = [
    "g",
    "y",
  ], run = "cd ~/.config/yazi/", desc = "Go to yazi config" },
  { on = [
    "g",
    "p",
  ], run = "cd ~/Pictures", desc = "Go to pictures" },
  { on = [
    "g",
    "r",
  ], run = "cd /", desc = "Go to /" },
  { on = [
    "g",
    "z",
  ], run = "cd ~/Zero/nix-config", desc = "Go to nixos config" },
  { on = [
    "g",
    "<Space>",
  ], run = "cd --interactive", desc = "Go by interactive" },

  # Help
  { on = [
    "?",
  ], run = "help", desc = "Open help" },
]

[tasks]

keymap = [
  { on = [
    "<Esc>",
  ], run = "close", desc = "Hide the task manager" },
  { on = [
    "<C-q>",
  ], run = "close", desc = "Hide the task manager" },
  { on = [
    "w",
  ], run = "close", desc = "Hide the task manager" },

  { on = [
    "k",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "j",
  ], run = "arrow 1", desc = "Move cursor down" },

  { on = [
    "<Up>",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "<Down>",
  ], run = "arrow 1", desc = "Move cursor down" },

  { on = [
    "<Enter>",
  ], run = "inspect", desc = "Inspect the task" },
  { on = [
    "x",
  ], run = "cancel", desc = "Cancel the task" },

  { on = [
    "?",
  ], run = "help", desc = "Open help" },
]

[select]

keymap = [
  { on = [
    "<C-q>",
  ], run = "close", desc = "Cancel selection" },
  { on = [
    "<Esc>",
  ], run = "close", desc = "Cancel selection" },
  { on = [
    "<Enter>",
  ], run = "close --submit", desc = "Submit the selection" },

  { on = [
    "k",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "j",
  ], run = "arrow 1", desc = "Move cursor down" },

  { on = [
    "K",
  ], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = [
    "J",
  ], run = "arrow 5", desc = "Move cursor down 5 lines" },

  { on = [
    "<Up>",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "<Down>",
  ], run = "arrow 1", desc = "Move cursor down" },


  { on = [
    "?",
  ], run = "help", desc = "Open help" },
]

[input]

keymap = [
  { on = [
    "<Backspace>",
  ], run = "backspace" },
  { on = [
    "<C-q>",
  ], run = "close", desc = "Cancel input" },
  { on = [
    "<Enter>",
  ], run = "close --submit", desc = "Submit the input" },
  { on = [
    "<Esc>",
  ], run = "escape", desc = "Go back the normal mode, or cancel input" },

  # Mode
  { on = [
    "i",
  ], run = "insert", desc = "Enter insert mode" },
  { on = [
    "a",
  ], run = "insert --append", desc = "Enter append mode" },
  { on = [
    "v",
  ], run = "visual", desc = "Enter visual mode" },

  # Navigation
  { on = [
    "h",
  ], run = "move -1", desc = "Move cursor left" },
  { on = [
    "l",
  ], run = "move 1", desc = "Move cursor right" },

  { on = [
    "0",
  ], run = "move -999", desc = "Move to the BOL" },
  { on = [
    "$",
  ], run = "move 999", desc = "Move to the EOL" },
  { on = [
    "I",
  ], run = [
    "move -999",
    "insert",
  ], desc = "Move to the BOL, and enter insert mode" },
  { on = [
    "A",
  ], run = [
    "move 999",
    "insert --append",
  ], desc = "Move to the EOL, and enter append mode" },
  { on = [
    "<C-a>",
  ], run = "move -999", desc = "Move to the BOL" },
  { on = [
    "<C-e>",
  ], run = "move 999", desc = "Move to the EOL" },

  { on = [
    "<Left>",
  ], run = "move -1", desc = "Move cursor left" },
  { on = [
    "<Right>",
  ], run = "move 1", desc = "Move cursor right" },

  { on = [
    "b",
  ], run = "backward", desc = "Move to the beginning of the previous word" },
  { on = [
    "w",
  ], run = "forward", desc = "Move to the beginning of the next word" },
  { on = [
    "e",
  ], run = "forward --end-of-word", desc = "Move to the end of the next word" },
  { on = [
    "H",
  ], run = "backward", desc = "Move to the beginning of the previous word" },
  { on = [
    "L",
  ], run = "forward --end-of-word", desc = "Move to the end of the next word" },

  # Deletion
  #'db' will delete a word before cursor, 'de' will delete a word after cursor
  #'d0' will delete all word before cursor, 'd$' will delete all word after cursor
  { on = [
    "d",
  ], run = "delete --cut", desc = "Cut the selected characters" },
  { on = [
    "c",
  ], run = "delete --cut --insert", desc = "Cut the selected characters, and enter insert mode" },
  { on = [
    "x",
  ], run = [
    "delete --cut",
    "move 1 --in-operating",
  ], desc = "Cut the current character" },

  # Yank/Paste
  { on = [
    "y",
  ], run = "yank", desc = "Copy the selected characters" },
  { on = [
    "p",
  ], run = "paste", desc = "Paste the copied characters after the cursor" },
  { on = [
    "P",
  ], run = "paste --before", desc = "Paste the copied characters before the cursor" },

  # Undo/Redo
  { on = [
    "u",
  ], run = "undo", desc = "Undo the last operation" },
  { on = [
    "<C-r>",
  ], run = "redo", desc = "Redo the last operation" },

  # Help
  { on = [
    "?",
  ], run = "help", desc = "Open help" },
]

[help]

keymap = [
  { on = [
    "<Esc>",
  ], run = "escape", desc = "Clear the filter, or hide the help" },
  { on = [
    "q",
  ], run = "close", desc = "Exit the process" },
  { on = [
    "<C-q>",
  ], run = "close", desc = "Hide the help" },

  # Navigation
  { on = [
    "k",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "j",
  ], run = "arrow 1", desc = "Move cursor down" },

  { on = [
    "K",
  ], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = [
    "J",
  ], run = "arrow 5", desc = "Move cursor down 5 lines" },

  { on = [
    "<Up>",
  ], run = "arrow -1", desc = "Move cursor up" },
  { on = [
    "<Down>",
  ], run = "arrow 1", desc = "Move cursor down" },

  # Filtering
  { on = [
    "/",
  ], run = "filter", desc = "Apply a filter for the help items" },
]

[confirm]
keymap = [
  { on = "<Esc>", run = "close", desc = "Cancel the confirm" },
  { on = "<C-[>", run = "close", desc = "Cancel the confirm" },
  { on = "<C-c>", run = "close", desc = "Cancel the confirm" },
  { on = "<Enter>", run = "close --submit", desc = "Submit the confirm" },

  { on = "n", run = "close", desc = "Cancel the confirm" },
  { on = "y", run = "close --submit", desc = "Submit the confirm" },

  { on = "k", run = "arrow -1", desc = "Move cursor up" },
  { on = "j", run = "arrow 1", desc = "Move cursor down" },

  { on = "K", run = "arrow -5", desc = "Move cursor up" },
  { on = "J", run = "arrow 5", desc = "Move cursor down" },

  { on = "<Up>", run = "arrow -1", desc = "Move cursor up" },
  { on = "<Down>", run = "arrow 1", desc = "Move cursor down" },

]


[[manager.prepend_keymap]]
on = ["c", "l"]
run = ["plugin clipboard"]
desc = "clip to clipboard"


# [[manager.prepend_keymap]]
# on  = [ "c","l" ]
# run = ['''
# 	shell --confirm 'for path in "$@"; do echo -en "file://${path}\n"; done | wl-copy -t text/uri-list; wl-paste | xclip -i -selection clipboard -rmlastnl -t text/uri-list'
# ''' ]
# desc = "clip to wayland clipboard"

# [[manager.prepend_keymap]]
# on  = [ "c","o" ]
# run = ['''
# 	shell --confirm 'for path in "$@"; do  echo -en "file://${path}\n"; done |  xclip -i -selection clipboard -rmlastnl -t text/uri-list'
# ''' ]
# desc = "clip to x11 clipboard"
